dist: trusty
sudo: false

language: python
python:
  - 3.6

install:
  - python setup.py sdist
  - pip install dist/*.tar.gz
  - pip install mock --upgrade
  - pip install coveralls

script:
  - coverage run --omit=pythesint/tests/* --source=pythesint setup.py test

after_success:
  - coveralls

deploy:
  - provider: pypi
    user: "__token__"
    password: "${PYPI_TOKEN}"
    skip_existing: true
    on:
      tags: true
