dist: trusty
sudo: false

language: python
python:
  - 2.7
  - 3.6

install:
  - python setup.py sdist
  - pip install dist/*.tar.gz
  - pip install mock --upgrade
  - pip install coveralls

script:
  - coverage run --omit=pythesint/tests/* --source=pythesint setup.py test

after_success:
  - coveralls

before_deploy:
  - >
    [[ "$(python --version 2>&1)" == *2.7* ]] &&
    wget -nv -O - https://bootstrap.pypa.io/pip/2.7/get-pip.py | python - --no-setuptools --no-wheel
deploy:
  - provider: pypi
    user: "__token__"
    password: "${PYPI_TOKEN}"
    skip_existing: true
    server: 'https://test.pypi.org/legacy/'
    on:
      tags: true
