language: python
python:
  - 2.7
sudo: false

install:
  - pip install coveralls

script: #"cd ..; nosetests --with-coverage --cover-package=nansat nansat.tests"
  - coverage run --source=nerscmetadata setup.py test

after_success:
  - coveralls

