language: python
python:
  - 2.7
sudo: false

install:
  - pip install .
  - pip install coveralls

script:
  - coverage run --omit=pythesint/tests/* --source=pythesint setup.py test

after_success:
  - coveralls

