language: python
python:
  - 2.7
sudo: false

install:
  - python setup.py sdist
  - pip install dist/*.tar.gz
  - pip install coveralls

script:
  - coverage run --source=pythesint setup.py test

after_success:
  - coveralls

