language: python
python:
  - 2.7
sudo: false

install:
  - pip install .
  - pip install coveralls
  - python -c 'import mock; print mock.__file__'

script:
  - coverage run --omit=pythesint/tests/* --source=pythesint setup.py test

after_success:
  - coveralls

