name: Run unit tests and build Python package
on:
  push:
    branches: ['**']
  release:
    types: [released]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - {'python': '3.6', 'latest': false}
          - {'python': '3.7', 'latest': false}
          - {'python': '3.8', 'latest': false}
          - {'python': '3.9', 'latest': false}
          - {'python': '3.10', 'latest': false}
          - {'python': '3.11', 'latest': true}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python.version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade coveralls mock wheel

    - name: Run unit tests
      run: coverage run --omit=pythesint/tests/* --source=pythesint setup.py test

    - name: Publish coverage
      if: ${{ matrix.version.latest }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: coveralls --service=github


  build_publish_package:
    runs-on: 'ubuntu-latest'
    needs: tests
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3'

    - name: Build Python package
      if: github.event_name == 'release'
      run: >
        PYTHESINT_RELEASE="${{ github.ref_name }}"
        python setup.py sdist bdist_wheel

    - name: Publish Python package
      if: github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        # Storing the PyPI URL in the repositories' secrets makes
        # publishing to the test PyPI from forks easy
        repository_url: ${{ secrets.PYPI_REPOSITORY_URL }}
        password: ${{ secrets.PYPI_TOKEN }}
